import { StyleSheet } from "react-native";

export const recipesScreenStyles = StyleSheet.create({
    container: {
        flex: 1,
    },
    headerBar: {
        height: 60,
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 20,
        borderBottomWidth: 1,
    },
    backBtn: {
        width: 36,
        height: 36,
        borderRadius: 18,
        borderWidth: 1,
        alignItems: "center",
        justifyContent: "center",
        marginRight: 12,
        marginTop: 5,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: "700",
    },
    searchContainer: {
        flexDirection: "row",
        alignItems: "center",
        marginHorizontal: 15,
        marginVertical: 10,
        paddingHorizontal: 15,
        borderRadius: 12,
        height: 50,
        elevation: 2,
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowRadius: 3,
    },
    searchInput: {
        flex: 1,
        marginLeft: 10,
        fontSize: 16,
    },
    tabsRow: {
        flexDirection: "row",
        gap: 10,
        paddingHorizontal: 15,
        marginBottom: 8,
    },
    tabButton: {
        flex: 1,
        borderWidth: 1,
        borderRadius: 12,
        paddingVertical: 10,
        alignItems: "center",
    },
    typeFilterPanel: {
        marginHorizontal: 15,
        marginBottom: 10,
        borderRadius: 14,
        borderWidth: 1,
        paddingHorizontal: 12,
        paddingVertical: 10,
        gap: 10,
    },
    typeFilterHeader: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    typeFilterHeaderLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    typeFiltersWrap: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
    },
    typeFilterChip: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        borderWidth: 1,
        borderRadius: 999,
        paddingHorizontal: 11,
        paddingVertical: 7,
    },
    errorBanner: {
        marginHorizontal: 15,
        marginBottom: 8,
        borderRadius: 12,
        borderWidth: 1,
        paddingHorizontal: 12,
        paddingVertical: 10,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    listContent: {
        paddingHorizontal: 15,
        paddingTop: 5,
    },
    fab: {
        position: "absolute",
        right: 20,
        width: 64,
        height: 64,
        borderRadius: 32,
        justifyContent: "center",
        alignItems: "center",
        elevation: 8,
        shadowColor: "#000",
        shadowOpacity: 0.3,
        shadowRadius: 5,
    },
});
