import { StyleSheet } from "react-native";

export const budgetAdvancesStyles = StyleSheet.create({
  container: { flex: 1 },
  content: { paddingTop: 0, paddingHorizontal: 16, paddingBottom: 40, gap: 12 },
  center: { flex: 1, alignItems: "center", justifyContent: "center" },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingBottom: 12,
    borderBottomWidth: 1,
    marginBottom: 2,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
  },
  title: { fontSize: 18, fontWeight: "700" },
  subtitle: { marginTop: 2, fontSize: 13, lineHeight: 18 },
  card: { borderWidth: 1, borderRadius: 14, padding: 12, gap: 8 },
  listWrap: { gap: 8 },
  innerCard: { borderWidth: 1, borderRadius: 10, padding: 10, gap: 6 },
  innerTitle: { fontSize: 14, fontWeight: "700" },
  text: { fontSize: 13, lineHeight: 18 },
  label: { fontSize: 13, fontWeight: "600" },
  input: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8, fontSize: 14 },
  actionsRow: { flexDirection: "row", gap: 8 },
  actionsWrap: { gap: 8 },
  actionBtn: {
    minHeight: 34,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  actionBtnText: { color: "#FFFFFF", fontWeight: "700", fontSize: 12, textAlign: "center" },
  historyHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
});
